import { FileText, Download, Eye, ChevronRight } from "lucide-react";

const SamplePreviewSection = () => {
  return (
    <section id="preview" className="py-24 relative bg-muted/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <span className="text-accent font-semibold text-sm uppercase tracking-wider">Sample Output</span>
          <h2 className="heading-section mt-4">
            See What Git2Doc Can
            <br />
            <span className="gradient-text">Generate For You</span>
          </h2>
          <p className="text-body max-w-2xl mx-auto mt-4">
            Here's an example of documentation generated from a real open-source repository.
          </p>
        </div>

        {/* Preview Container */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          {/* PDF Preview */}
          <div className="gradient-border p-1 rounded-2xl">
            <div className="bg-card rounded-xl overflow-hidden">
              {/* PDF Header */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-muted/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-red-500/20 flex items-center justify-center">
                    <FileText className="w-5 h-5 text-red-400" />
                  </div>
                  <div>
                    <p className="font-semibold">react-todo-app-docs.pdf</p>
                    <p className="text-xs text-muted-foreground">Generated from github.com/example/react-todo</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button className="p-2 rounded-lg hover:bg-muted transition-colors">
                    <Eye className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded-lg hover:bg-muted transition-colors">
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* PDF Content Preview */}
              <div className="p-8 space-y-6 max-h-[600px] overflow-y-auto">
                {/* Title Page */}
                <div className="text-center pb-8 border-b border-border">
                  <h3 className="text-3xl font-bold gradient-text mb-2">React Todo Application</h3>
                  <p className="text-muted-foreground">Technical Documentation</p>
                  <p className="text-sm text-muted-foreground mt-4">Generated by Git2Doc AI</p>
                </div>

                {/* Table of Contents */}
                <div>
                  <h4 className="font-semibold text-lg mb-4">Table of Contents</h4>
                  <ul className="space-y-2 text-sm">
                    {[
                      "1. Project Overview",
                      "2. Architecture",
                      "3. Component Reference",
                      "4. API Documentation",
                      "5. State Management",
                      "6. Getting Started",
                    ].map((item) => (
                      <li key={item} className="flex items-center gap-2 text-muted-foreground hover:text-foreground cursor-pointer">
                        <ChevronRight className="w-4 h-4" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Sample Section */}
                <div>
                  <h4 className="font-semibold text-lg mb-4">1. Project Overview</h4>
                  <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                    This React Todo Application is a modern task management system built with React 18, 
                    TypeScript, and Tailwind CSS. It features a clean, responsive UI with support for 
                    creating, editing, and organizing tasks.
                  </p>
                  
                  <h5 className="font-medium mb-2">Key Technologies</h5>
                  <ul className="text-sm text-muted-foreground space-y-1">
                    <li>• React 18 with Hooks</li>
                    <li>• TypeScript for type safety</li>
                    <li>• Tailwind CSS for styling</li>
                    <li>• Zustand for state management</li>
                  </ul>
                </div>

                {/* Component Section */}
                <div>
                  <h4 className="font-semibold text-lg mb-4">3. Component Reference</h4>
                  
                  <div className="bg-muted/50 rounded-lg p-4 mb-4">
                    <code className="text-sm font-mono text-primary">{"<TodoList />"}</code>
                    <p className="text-sm text-muted-foreground mt-2">
                      Main container component that renders the list of todos and handles 
                      filtering and sorting logic.
                    </p>
                    <div className="mt-3">
                      <span className="text-xs font-semibold text-muted-foreground">Props:</span>
                      <ul className="text-xs text-muted-foreground mt-1">
                        <li>• filter: 'all' | 'active' | 'completed'</li>
                        <li>• onToggle: (id: string) =&gt; void</li>
                      </ul>
                    </div>
                  </div>

                  <div className="bg-muted/50 rounded-lg p-4">
                    <code className="text-sm font-mono text-secondary">{"<TodoItem />"}</code>
                    <p className="text-sm text-muted-foreground mt-2">
                      Individual todo item component with edit and delete capabilities.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Features List */}
          <div className="space-y-6">
            <h3 className="heading-card">What's Included in Every Document</h3>
            
            {[
              {
                title: "Project Overview",
                description: "High-level summary of your project's purpose, tech stack, and architecture.",
              },
              {
                title: "Component Documentation",
                description: "Detailed docs for every component including props, usage examples, and relationships.",
              },
              {
                title: "API Reference",
                description: "Complete API documentation with endpoints, request/response schemas, and examples.",
              },
              {
                title: "Architecture Diagrams",
                description: "Visual diagrams showing data flow, component hierarchy, and system design.",
              },
              {
                title: "Code Examples",
                description: "Real code snippets with explanations for complex functionality.",
              },
              {
                title: "Getting Started Guide",
                description: "Step-by-step setup instructions for new developers joining your project.",
              },
            ].map((item, index) => (
              <div key={item.title} className="flex gap-4 group">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary/20 to-secondary/20 flex items-center justify-center flex-shrink-0 group-hover:from-primary/30 group-hover:to-secondary/30 transition-all">
                  <span className="text-sm font-bold text-primary">{index + 1}</span>
                </div>
                <div>
                  <h4 className="font-semibold mb-1">{item.title}</h4>
                  <p className="text-small">{item.description}</p>
                </div>
              </div>
            ))}

            <div className="pt-6">
              <a href="#pricing" className="btn-primary">
                Try It Free <ChevronRight className="w-4 h-4" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SamplePreviewSection;
